services:
  - type: web
    name: docling-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
